NUM_GPUS: 0
TRAIN:
  ENABLE: False
TEST:
  ENABLE: False
  CHECKPOINT_TEST_PATH: path/to/your/checkpoint
INFER:
  ENABLE: True
DATASET:
  DATASET_NAME: Custom
  ROOT_DIR: path/to/your/datasets/root
  TEST_INFO_TXT: ''
  IMG_SIZE: 320
  SCALE_RATE: 8/7
  ROTATE_ANGLE: 10
  CUTOUT_H: 10
  CUTOUT_W: 10
  COMPRESSION_LOW: 65
  COMPRESSION_HIGH: 80
DATALOADER:
  BATCH_SIZE: 8
  NUM_WORKERS: 0
LOSS:
  LOSS_FUN: FocalLoss
  LOSS_WEIGHT: 1
  logits: True
MODEL:
  MODEL_NAME: M2TR
  PRETRAINED: 'imagenet'
  ESCAPE: ''
  IMG_SIZE: 320
  BACKBONE: efficientnet-b4
  DEPTH: 4
  TEXTURE_LAYER: b2
  FEATURE_LAYER: final
  NUM_CLASSES: 2
  DROP_RATIO: 0.5
  HAS_DECODER: True
OPTIMIZER:
  OPTIMIZER_METHOD: sgd
  BASE_LR: 0.0005
  EPS: 0.00000001
  MOMENTUM: 0.9
